# KGC ERP v3.0 - pnpm Monorepo Workspace
# ADR-010: Micro-modules architektúra (Struktúra B - Nested by Layer)

packages:
  - 'apps/*'
  - 'packages/core/*'
  - 'packages/shared/*'
  - 'packages/berles/*'
  - 'packages/szerviz/*'
  - 'packages/aruhaz/*'
  - 'packages/integration/*'
