// Mock Data for Worksheet Wizard
import type { Partner } from '../rental/types';
import type { LaborNorm, Part, Product, Worksheet } from './types';
import {
  ProductCategory,
  WorksheetHistoryAction,
  WorksheetPriority,
  WorksheetStatus,
  WorksheetType,
} from './types';

// Reuse partners from rental
export const MOCK_PARTNERS: Partner[] = [
  {
    id: 'p1',
    name: 'Kovács Építőipari Kft.',
    email: 'kovacs@epito.hu',
    phone: '+36 30 123 4567',
    taxNumber: '12345678-2-42',
    type: 'COMPANY',
    isVip: true,
    creditLimit: 500000,
    balance: 0,
  },
  {
    id: 'p2',
    name: 'Nagy János EV',
    email: 'nagy.janos@gmail.com',
    phone: '+36 70 234 5678',
    taxNumber: '87654321-1-41',
    type: 'INDIVIDUAL',
    isVip: false,
    creditLimit: 100000,
    balance: 0,
  },
  {
    id: 'p3',
    name: 'Szabó és Társa Bt.',
    email: 'info@szabobt.hu',
    phone: '+36 20 345 6789',
    taxNumber: '11223344-2-43',
    type: 'COMPANY',
    isVip: false,
    creditLimit: 200000,
    balance: 0,
  },
  {
    id: 'p4',
    name: 'Pintér Kertészet',
    email: 'pinter@kerteszet.hu',
    phone: '+36 30 456 7890',
    taxNumber: '55667788-1-42',
    type: 'COMPANY',
    isVip: true,
    creditLimit: 300000,
    balance: 0,
  },
  {
    id: 'p5',
    name: 'Magyar Tisztító Kft.',
    email: 'info@magyartisztito.hu',
    phone: '+36 70 567 8901',
    taxNumber: '99887766-2-41',
    type: 'COMPANY',
    isVip: false,
    creditLimit: 150000,
    balance: 0,
  },
];

// Mock products/equipment for service
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod1',
    name: 'Makita HR2470 Fúrókalapács',
    brand: 'Makita',
    model: 'HR2470',
    serialNumber: 'MK-2024-001234',
    category: ProductCategory.POWER_TOOL,
    warrantyExpiry: new Date('2025-06-15'),
    purchaseDate: new Date('2023-06-15'),
  },
  {
    id: 'prod2',
    name: 'Bosch GBH 2-26 DRE Fúrókalapács',
    brand: 'Bosch',
    model: 'GBH 2-26 DRE',
    serialNumber: 'BSH-2023-005678',
    category: ProductCategory.POWER_TOOL,
    warrantyExpiry: new Date('2024-03-20'),
    purchaseDate: new Date('2022-03-20'),
  },
  {
    id: 'prod3',
    name: 'Stihl MS 170 Láncfűrész',
    brand: 'Stihl',
    model: 'MS 170',
    serialNumber: 'STL-2024-009876',
    category: ProductCategory.GARDEN,
    warrantyExpiry: new Date('2026-01-10'),
    purchaseDate: new Date('2024-01-10'),
  },
  {
    id: 'prod4',
    name: 'Husqvarna Automower 315X',
    brand: 'Husqvarna',
    model: 'Automower 315X',
    serialNumber: 'HVN-2023-112233',
    category: ProductCategory.GARDEN,
    warrantyExpiry: new Date('2025-09-01'),
    purchaseDate: new Date('2023-09-01'),
  },
  {
    id: 'prod5',
    name: 'Kärcher K5 Premium Magasnyomású mosó',
    brand: 'Kärcher',
    model: 'K5 Premium',
    serialNumber: 'KRC-2024-445566',
    category: ProductCategory.CLEANING,
    warrantyExpiry: new Date('2026-04-15'),
    purchaseDate: new Date('2024-04-15'),
  },
  {
    id: 'prod6',
    name: 'Hilti TE 30-A36 Akkus fúrókalapács',
    brand: 'Hilti',
    model: 'TE 30-A36',
    serialNumber: 'HLT-2023-778899',
    category: ProductCategory.CONSTRUCTION,
    warrantyExpiry: new Date('2025-11-20'),
    purchaseDate: new Date('2023-11-20'),
  },
];

// Mock parts inventory
export const MOCK_PARTS: Part[] = [
  {
    id: 'part1',
    name: 'Szénkefe készlet (2db)',
    sku: 'MK-CB-001',
    unitPrice: 2500,
    inStock: 45,
    category: 'Elektromos',
  },
  {
    id: 'part2',
    name: 'O-gyűrű készlet',
    sku: 'MK-OR-002',
    unitPrice: 1200,
    inStock: 120,
    category: 'Tömítés',
  },
  {
    id: 'part3',
    name: 'Ütvető dugattyú',
    sku: 'MK-HP-003',
    unitPrice: 8500,
    inStock: 12,
    category: 'Mechanika',
  },
  {
    id: 'part4',
    name: 'Kapcsoló modul',
    sku: 'MK-SW-004',
    unitPrice: 4800,
    inStock: 28,
    category: 'Elektromos',
  },
  {
    id: 'part5',
    name: 'Tokmány SDS-Plus',
    sku: 'GEN-CH-005',
    unitPrice: 12500,
    inStock: 8,
    category: 'Tartozék',
  },
  {
    id: 'part6',
    name: 'Kábel 3m H07RN-F',
    sku: 'GEN-CB-006',
    unitPrice: 3200,
    inStock: 35,
    category: 'Elektromos',
  },
  {
    id: 'part7',
    name: 'Csapágy készlet 608ZZ',
    sku: 'GEN-BR-007',
    unitPrice: 1800,
    inStock: 65,
    category: 'Mechanika',
  },
  {
    id: 'part8',
    name: 'Fogaskerék hajtómű',
    sku: 'MK-GR-008',
    unitPrice: 15200,
    inStock: 5,
    category: 'Mechanika',
  },
  {
    id: 'part9',
    name: 'Láncfűrész lánc 35cm',
    sku: 'STL-CH-009',
    unitPrice: 6800,
    inStock: 22,
    category: 'Tartozék',
  },
  {
    id: 'part10',
    name: 'Légszűrő',
    sku: 'GEN-AF-010',
    unitPrice: 2100,
    inStock: 40,
    category: 'Szűrő',
  },
];

// Mock labor norms (Makita style)
export const MOCK_LABOR_NORMS: LaborNorm[] = [
  {
    id: 'norm1',
    code: 'SZ-001',
    description: 'Szénkefe csere',
    minutes: 15,
    hourlyRate: 8000,
    calculatedPrice: 2000,
  },
  {
    id: 'norm2',
    code: 'SZ-002',
    description: 'Kapcsoló csere',
    minutes: 30,
    hourlyRate: 8000,
    calculatedPrice: 4000,
  },
  {
    id: 'norm3',
    code: 'SZ-003',
    description: 'Kábel csere',
    minutes: 45,
    hourlyRate: 8000,
    calculatedPrice: 6000,
  },
  {
    id: 'norm4',
    code: 'SZ-004',
    description: 'Tokmány csere',
    minutes: 20,
    hourlyRate: 8000,
    calculatedPrice: 2667,
  },
  {
    id: 'norm5',
    code: 'SZ-005',
    description: 'Csapágy csere',
    minutes: 60,
    hourlyRate: 8000,
    calculatedPrice: 8000,
  },
  {
    id: 'norm6',
    code: 'SZ-006',
    description: 'Hajtómű javítás',
    minutes: 90,
    hourlyRate: 8000,
    calculatedPrice: 12000,
  },
  {
    id: 'norm7',
    code: 'SZ-007',
    description: 'Ütvető mechanika javítás',
    minutes: 75,
    hourlyRate: 8000,
    calculatedPrice: 10000,
  },
  {
    id: 'norm8',
    code: 'SZ-008',
    description: 'Teljes szétszerelés + tisztítás',
    minutes: 45,
    hourlyRate: 8000,
    calculatedPrice: 6000,
  },
  {
    id: 'norm9',
    code: 'SZ-009',
    description: 'Diagnosztika',
    minutes: 15,
    hourlyRate: 8000,
    calculatedPrice: 2000,
  },
  {
    id: 'norm10',
    code: 'SZ-010',
    description: 'Karbantartás (alapszintű)',
    minutes: 30,
    hourlyRate: 8000,
    calculatedPrice: 4000,
  },
];

// Helper: Check if product is under warranty
export function isUnderWarranty(product: Product): boolean {
  if (!product.warrantyExpiry) return false;
  return new Date() < product.warrantyExpiry;
}

// Helper: Calculate item totals
export function calculateItemTotal(
  unitPrice: number,
  quantity: number,
  vatRate: number = 27
): {
  netAmount: number;
  grossAmount: number;
} {
  const netAmount = unitPrice * quantity;
  const grossAmount = Math.round(netAmount * (1 + vatRate / 100));
  return { netAmount, grossAmount };
}

// Helper: Calculate labor price from norm
export function calculateLaborPrice(norm: LaborNorm, quantity: number = 1): number {
  return Math.round((norm.minutes / 60) * norm.hourlyRate * quantity);
}

// Mock worksheets
export const MOCK_WORKSHEETS: Worksheet[] = [
  {
    id: 'ws-001',
    worksheetNumber: 'ML-2026-0001',
    partnerId: 'p1',
    partnerName: 'Kovács Építőipari Kft.',
    partnerPhone: '+36 30 123 4567',
    partnerEmail: 'kovacs@epito.hu',
    product: MOCK_PRODUCTS[0]!,
    worksheetType: WorksheetType.FIZETOS,
    priority: WorksheetPriority.NORMAL,
    status: WorksheetStatus.FOLYAMATBAN,
    faultDescription: 'A gép nem indul be, szikrázik a motorháznál.',
    diagnosis: 'Elkopott szénkefék, tokmány sérült.',
    workPerformed: 'Szénkefe csere elvégezve, tokmány csere folyamatban.',
    items: [
      {
        id: 'i1',
        type: 'ALKATRESZ',
        description: 'Szénkefe készlet (2db)',
        quantity: 1,
        unitPrice: 2500,
        vatRate: 27,
        netAmount: 2500,
        grossAmount: 3175,
        partId: 'part1',
      },
      {
        id: 'i2',
        type: 'ALKATRESZ',
        description: 'Tokmány SDS-Plus',
        quantity: 1,
        unitPrice: 12500,
        vatRate: 27,
        netAmount: 12500,
        grossAmount: 15875,
        partId: 'part5',
      },
      {
        id: 'i3',
        type: 'MUNKADIJ',
        description: 'Szénkefe csere',
        quantity: 1,
        unitPrice: 2000,
        vatRate: 27,
        netAmount: 2000,
        grossAmount: 2540,
        normId: 'norm1',
      },
      {
        id: 'i4',
        type: 'MUNKADIJ',
        description: 'Tokmány csere',
        quantity: 1,
        unitPrice: 2667,
        vatRate: 27,
        netAmount: 2667,
        grossAmount: 3387,
        normId: 'norm4',
      },
    ],
    costLimit: 50000,
    netTotal: 19667,
    vatTotal: 5310,
    grossTotal: 24977,
    depositPaid: 10000,
    createdAt: '2026-01-15T09:30:00Z',
    updatedAt: '2026-01-17T14:20:00Z',
    estimatedCompletionDate: '2026-01-20',
    completedAt: null,
    invoicedAt: null,
    createdBy: 'Nagy Éva',
    assignedTo: 'Szabó Péter',
    internalNote: 'Ügyfél várja a visszajelzést, telefon előnyben.',
    customerNote: 'Kérem sürgősen javítsák, mert holnap kellene.',
    history: [
      {
        id: 'h1',
        timestamp: '2026-01-15T09:30:00Z',
        action: WorksheetHistoryAction.CREATED,
        description: 'Munkalap létrehozva',
        userId: 'u1',
        userName: 'Nagy Éva',
      },
      {
        id: 'h2',
        timestamp: '2026-01-15T10:00:00Z',
        action: WorksheetHistoryAction.ASSIGNED,
        description: 'Hozzárendelve: Szabó Péter',
        userId: 'u1',
        userName: 'Nagy Éva',
        newValue: 'Szabó Péter',
      },
      {
        id: 'h3',
        timestamp: '2026-01-16T08:30:00Z',
        action: WorksheetHistoryAction.STATUS_CHANGED,
        description: 'Státusz: Folyamatban',
        userId: 'u2',
        userName: 'Szabó Péter',
        oldValue: 'Felvéve',
        newValue: 'Folyamatban',
      },
      {
        id: 'h4',
        timestamp: '2026-01-16T09:15:00Z',
        action: WorksheetHistoryAction.ITEM_ADDED,
        description: 'Tétel: Szénkefe készlet (2db)',
        userId: 'u2',
        userName: 'Szabó Péter',
      },
      {
        id: 'h5',
        timestamp: '2026-01-17T14:20:00Z',
        action: WorksheetHistoryAction.ITEM_ADDED,
        description: 'Tétel: Tokmány SDS-Plus',
        userId: 'u2',
        userName: 'Szabó Péter',
      },
    ],
  },
  {
    id: 'ws-002',
    worksheetNumber: 'ML-2026-0002',
    partnerId: 'p2',
    partnerName: 'Nagy János EV',
    partnerPhone: '+36 70 234 5678',
    partnerEmail: 'nagy.janos@gmail.com',
    product: MOCK_PRODUCTS[2]!,
    worksheetType: WorksheetType.GARANCIALIS,
    priority: WorksheetPriority.GARANCIALIS,
    status: WorksheetStatus.KESZ,
    faultDescription: 'Láncfűrész nem olajoz, lánc túlmelegszik.',
    diagnosis: 'Olajszivattyú dugulás, légszűrő eldugult.',
    workPerformed: 'Olajrendszer átmosva, légszűrő cserélve, teszt OK.',
    items: [
      {
        id: 'i5',
        type: 'ALKATRESZ',
        description: 'Légszűrő',
        quantity: 1,
        unitPrice: 0,
        vatRate: 27,
        netAmount: 0,
        grossAmount: 0,
        partId: 'part10',
      },
      {
        id: 'i6',
        type: 'MUNKADIJ',
        description: 'Karbantartás (alapszintű)',
        quantity: 1,
        unitPrice: 0,
        vatRate: 27,
        netAmount: 0,
        grossAmount: 0,
        normId: 'norm10',
      },
    ],
    costLimit: null,
    netTotal: 0,
    vatTotal: 0,
    grossTotal: 0,
    depositPaid: 0,
    createdAt: '2026-01-10T11:00:00Z',
    updatedAt: '2026-01-14T16:30:00Z',
    estimatedCompletionDate: '2026-01-14',
    completedAt: '2026-01-14T16:30:00Z',
    invoicedAt: null,
    createdBy: 'Kiss Anna',
    assignedTo: 'Tóth Gábor',
    internalNote: 'Garanciális, Stihl elszámolásba.',
    customerNote: '',
    history: [
      {
        id: 'h6',
        timestamp: '2026-01-10T11:00:00Z',
        action: WorksheetHistoryAction.CREATED,
        description: 'Munkalap létrehozva',
        userId: 'u3',
        userName: 'Kiss Anna',
      },
      {
        id: 'h7',
        timestamp: '2026-01-10T11:30:00Z',
        action: WorksheetHistoryAction.ASSIGNED,
        description: 'Hozzárendelve: Tóth Gábor',
        userId: 'u3',
        userName: 'Kiss Anna',
        newValue: 'Tóth Gábor',
      },
      {
        id: 'h8',
        timestamp: '2026-01-12T09:00:00Z',
        action: WorksheetHistoryAction.STATUS_CHANGED,
        description: 'Státusz: Folyamatban',
        userId: 'u4',
        userName: 'Tóth Gábor',
        oldValue: 'Felvéve',
        newValue: 'Folyamatban',
      },
      {
        id: 'h9',
        timestamp: '2026-01-14T16:30:00Z',
        action: WorksheetHistoryAction.COMPLETED,
        description: 'Javítás befejezve',
        userId: 'u4',
        userName: 'Tóth Gábor',
      },
      {
        id: 'h10',
        timestamp: '2026-01-14T16:30:00Z',
        action: WorksheetHistoryAction.STATUS_CHANGED,
        description: 'Státusz: Kész',
        userId: 'u4',
        userName: 'Tóth Gábor',
        oldValue: 'Folyamatban',
        newValue: 'Kész',
      },
    ],
  },
  {
    id: 'ws-003',
    worksheetNumber: 'ML-2026-0003',
    partnerId: 'p4',
    partnerName: 'Pintér Kertészet',
    partnerPhone: '+36 30 456 7890',
    partnerEmail: 'pinter@kerteszet.hu',
    product: MOCK_PRODUCTS[3]!,
    worksheetType: WorksheetType.FIZETOS,
    priority: WorksheetPriority.SURGOS,
    status: WorksheetStatus.FELVEVE,
    faultDescription: 'Robotfűnyíró nem tölti magát, nem talál haza.',
    diagnosis: '',
    workPerformed: '',
    items: [],
    costLimit: 100000,
    netTotal: 0,
    vatTotal: 0,
    grossTotal: 0,
    depositPaid: 20000,
    createdAt: '2026-01-18T08:00:00Z',
    updatedAt: '2026-01-18T08:00:00Z',
    estimatedCompletionDate: null,
    completedAt: null,
    invoicedAt: null,
    createdBy: 'Nagy Éva',
    assignedTo: null,
    internalNote: 'VIP ügyfél, sürgős!',
    customerNote: 'A fű nagyon hosszú már, kérem mielőbb nézék meg.',
    history: [
      {
        id: 'h11',
        timestamp: '2026-01-18T08:00:00Z',
        action: WorksheetHistoryAction.CREATED,
        description: 'Munkalap létrehozva',
        userId: 'u1',
        userName: 'Nagy Éva',
      },
    ],
  },
  {
    id: 'ws-004',
    worksheetNumber: 'ML-2026-0004',
    partnerId: 'p5',
    partnerName: 'Magyar Tisztító Kft.',
    partnerPhone: '+36 70 567 8901',
    partnerEmail: 'info@magyartisztito.hu',
    product: MOCK_PRODUCTS[4]!,
    worksheetType: WorksheetType.KARBANTARTAS,
    priority: WorksheetPriority.NORMAL,
    status: WorksheetStatus.SZAMLAZANDO,
    faultDescription: 'Éves karbantartás.',
    diagnosis: 'Normál kopás, minden rendben.',
    workPerformed: 'Tömítések ellenőrizve, szűrők tisztítva, nyomáspróba OK.',
    items: [
      {
        id: 'i7',
        type: 'ALKATRESZ',
        description: 'O-gyűrű készlet',
        quantity: 1,
        unitPrice: 1200,
        vatRate: 27,
        netAmount: 1200,
        grossAmount: 1524,
        partId: 'part2',
      },
      {
        id: 'i8',
        type: 'MUNKADIJ',
        description: 'Karbantartás (alapszintű)',
        quantity: 1,
        unitPrice: 4000,
        vatRate: 27,
        netAmount: 4000,
        grossAmount: 5080,
        normId: 'norm10',
      },
      {
        id: 'i9',
        type: 'MUNKADIJ',
        description: 'Diagnosztika',
        quantity: 1,
        unitPrice: 2000,
        vatRate: 27,
        netAmount: 2000,
        grossAmount: 2540,
        normId: 'norm9',
      },
    ],
    costLimit: null,
    netTotal: 7200,
    vatTotal: 1944,
    grossTotal: 9144,
    depositPaid: 0,
    createdAt: '2026-01-12T14:00:00Z',
    updatedAt: '2026-01-16T11:00:00Z',
    estimatedCompletionDate: '2026-01-16',
    completedAt: '2026-01-16T11:00:00Z',
    invoicedAt: null,
    createdBy: 'Kiss Anna',
    assignedTo: 'Szabó Péter',
    internalNote: '',
    customerNote: 'Számla e-mailben kérve.',
    history: [
      {
        id: 'h12',
        timestamp: '2026-01-12T14:00:00Z',
        action: WorksheetHistoryAction.CREATED,
        description: 'Munkalap létrehozva',
        userId: 'u3',
        userName: 'Kiss Anna',
      },
      {
        id: 'h13',
        timestamp: '2026-01-13T08:00:00Z',
        action: WorksheetHistoryAction.ASSIGNED,
        description: 'Hozzárendelve: Szabó Péter',
        userId: 'u3',
        userName: 'Kiss Anna',
        newValue: 'Szabó Péter',
      },
      {
        id: 'h14',
        timestamp: '2026-01-14T09:00:00Z',
        action: WorksheetHistoryAction.STATUS_CHANGED,
        description: 'Státusz: Folyamatban',
        userId: 'u2',
        userName: 'Szabó Péter',
        oldValue: 'Felvéve',
        newValue: 'Folyamatban',
      },
      {
        id: 'h15',
        timestamp: '2026-01-16T11:00:00Z',
        action: WorksheetHistoryAction.COMPLETED,
        description: 'Karbantartás befejezve',
        userId: 'u2',
        userName: 'Szabó Péter',
      },
      {
        id: 'h16',
        timestamp: '2026-01-16T11:00:00Z',
        action: WorksheetHistoryAction.STATUS_CHANGED,
        description: 'Státusz: Számlázandó',
        userId: 'u2',
        userName: 'Szabó Péter',
        oldValue: 'Folyamatban',
        newValue: 'Számlázandó',
      },
    ],
  },
  {
    id: 'ws-005',
    worksheetNumber: 'ML-2025-0089',
    partnerId: 'p3',
    partnerName: 'Szabó és Társa Bt.',
    partnerPhone: '+36 20 345 6789',
    partnerEmail: 'info@szabobt.hu',
    product: MOCK_PRODUCTS[5]!,
    worksheetType: WorksheetType.FIZETOS,
    priority: WorksheetPriority.NORMAL,
    status: WorksheetStatus.LEZART,
    faultDescription: 'Fúrókalapács ütésereje csökkent.',
    diagnosis: 'Ütvető dugattyú kopott, csapágyak cserélendők.',
    workPerformed: 'Teljes ütvető mechanika felújítva, csapágyak cserélve, teszt sikeres.',
    items: [
      {
        id: 'i10',
        type: 'ALKATRESZ',
        description: 'Ütvető dugattyú',
        quantity: 1,
        unitPrice: 8500,
        vatRate: 27,
        netAmount: 8500,
        grossAmount: 10795,
        partId: 'part3',
      },
      {
        id: 'i11',
        type: 'ALKATRESZ',
        description: 'Csapágy készlet 608ZZ',
        quantity: 2,
        unitPrice: 1800,
        vatRate: 27,
        netAmount: 3600,
        grossAmount: 4572,
        partId: 'part7',
      },
      {
        id: 'i12',
        type: 'MUNKADIJ',
        description: 'Ütvető mechanika javítás',
        quantity: 1,
        unitPrice: 10000,
        vatRate: 27,
        netAmount: 10000,
        grossAmount: 12700,
        normId: 'norm7',
      },
      {
        id: 'i13',
        type: 'MUNKADIJ',
        description: 'Csapágy csere',
        quantity: 1,
        unitPrice: 8000,
        vatRate: 27,
        netAmount: 8000,
        grossAmount: 10160,
        normId: 'norm5',
      },
    ],
    costLimit: 60000,
    netTotal: 30100,
    vatTotal: 8127,
    grossTotal: 38227,
    depositPaid: 15000,
    createdAt: '2025-12-20T10:00:00Z',
    updatedAt: '2026-01-05T15:00:00Z',
    estimatedCompletionDate: '2025-12-28',
    completedAt: '2025-12-27T14:00:00Z',
    invoicedAt: '2026-01-05T15:00:00Z',
    createdBy: 'Nagy Éva',
    assignedTo: 'Tóth Gábor',
    internalNote: 'Kifizetve, lezárva.',
    customerNote: '',
    history: [
      {
        id: 'h17',
        timestamp: '2025-12-20T10:00:00Z',
        action: WorksheetHistoryAction.CREATED,
        description: 'Munkalap létrehozva',
        userId: 'u1',
        userName: 'Nagy Éva',
      },
      {
        id: 'h18',
        timestamp: '2025-12-20T10:30:00Z',
        action: WorksheetHistoryAction.ASSIGNED,
        description: 'Hozzárendelve: Tóth Gábor',
        userId: 'u1',
        userName: 'Nagy Éva',
        newValue: 'Tóth Gábor',
      },
      {
        id: 'h19',
        timestamp: '2025-12-21T08:00:00Z',
        action: WorksheetHistoryAction.STATUS_CHANGED,
        description: 'Státusz: Folyamatban',
        userId: 'u4',
        userName: 'Tóth Gábor',
        oldValue: 'Felvéve',
        newValue: 'Folyamatban',
      },
      {
        id: 'h20',
        timestamp: '2025-12-27T14:00:00Z',
        action: WorksheetHistoryAction.COMPLETED,
        description: 'Javítás befejezve',
        userId: 'u4',
        userName: 'Tóth Gábor',
      },
      {
        id: 'h21',
        timestamp: '2026-01-05T15:00:00Z',
        action: WorksheetHistoryAction.INVOICED,
        description: 'Számla kiállítva: SZ-2026-0001',
        userId: 'u3',
        userName: 'Kiss Anna',
      },
      {
        id: 'h22',
        timestamp: '2026-01-05T15:00:00Z',
        action: WorksheetHistoryAction.STATUS_CHANGED,
        description: 'Státusz: Lezárt',
        userId: 'u3',
        userName: 'Kiss Anna',
        oldValue: 'Számlázandó',
        newValue: 'Lezárt',
      },
    ],
  },
];

// Helper: Format currency
export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('hu-HU', {
    style: 'currency',
    currency: 'HUF',
    maximumFractionDigits: 0,
  }).format(amount);
}

// Helper: Format date
export function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleDateString('hu-HU', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  });
}

// Helper: Format datetime
export function formatDateTime(dateString: string): string {
  return new Date(dateString).toLocaleString('hu-HU', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  });
}
