import type { Chat, ChatMessage, ChatUser } from './types';

export const CURRENT_USER: ChatUser = {
  id: 'user-me',
  name: 'Kiss Péter',
  status: 'online',
  role: 'Üzletvezető',
};

export const MOCK_USERS: ChatUser[] = [
  { id: 'user-1', name: 'Nagy Anna', status: 'online', role: 'Pénztáros' },
  { id: 'user-2', name: 'Szabó Ferenc', status: 'away', role: 'Szerelő' },
  { id: 'user-3', name: 'Horváth Mária', status: 'offline', role: 'Adminisztrátor' },
  { id: 'user-4', name: 'Kovács János', status: 'online', role: 'Raktáros' },
  { id: 'user-5', name: 'Tóth Gábor', status: 'online', role: 'Szerelő' },
];

export const MOCK_CHATS: Chat[] = [
  {
    id: 'chat-1',
    type: 'direct',
    name: 'Nagy Anna',
    participants: [CURRENT_USER, MOCK_USERS[0]!],
    lastMessage: {
      id: 'msg-1-5',
      chatId: 'chat-1',
      senderId: 'user-1',
      senderName: 'Nagy Anna',
      content: 'Rendben, megcsináltam a zárást!',
      timestamp: '2024-01-18T14:32:00Z',
      status: 'read',
    },
    unreadCount: 0,
    updatedAt: '2024-01-18T14:32:00Z',
  },
  {
    id: 'chat-2',
    type: 'group',
    name: 'Szerviz csapat',
    participants: [CURRENT_USER, MOCK_USERS[1]!, MOCK_USERS[4]!],
    lastMessage: {
      id: 'msg-2-3',
      chatId: 'chat-2',
      senderId: 'user-2',
      senderName: 'Szabó Ferenc',
      content: 'A Makita fúró alkatrész megérkezett',
      timestamp: '2024-01-18T13:15:00Z',
      status: 'delivered',
    },
    unreadCount: 2,
    updatedAt: '2024-01-18T13:15:00Z',
  },
  {
    id: 'chat-3',
    type: 'direct',
    name: 'Kovács János',
    participants: [CURRENT_USER, MOCK_USERS[3]!],
    lastMessage: {
      id: 'msg-3-2',
      chatId: 'chat-3',
      senderId: 'user-me',
      senderName: 'Kiss Péter',
      content: 'Kérlek ellenőrizd a készletet holnapig',
      timestamp: '2024-01-18T10:00:00Z',
      status: 'read',
      isOwn: true,
    },
    unreadCount: 0,
    updatedAt: '2024-01-18T10:00:00Z',
  },
  {
    id: 'chat-4',
    type: 'group',
    name: 'Vezetőség',
    participants: [CURRENT_USER, MOCK_USERS[2]!],
    lastMessage: {
      id: 'msg-4-1',
      chatId: 'chat-4',
      senderId: 'user-3',
      senderName: 'Horváth Mária',
      content: 'A havi jelentés elkészült, csatoltam',
      timestamp: '2024-01-17T16:45:00Z',
      status: 'read',
    },
    unreadCount: 0,
    updatedAt: '2024-01-17T16:45:00Z',
  },
  {
    id: 'chat-5',
    type: 'direct',
    name: 'Tóth Gábor',
    participants: [CURRENT_USER, MOCK_USERS[4]!],
    lastMessage: {
      id: 'msg-5-1',
      chatId: 'chat-5',
      senderId: 'user-5',
      senderName: 'Tóth Gábor',
      content: 'Szia! Holnap be tudnál jönni korábban?',
      timestamp: '2024-01-18T15:00:00Z',
      status: 'delivered',
    },
    unreadCount: 1,
    updatedAt: '2024-01-18T15:00:00Z',
  },
];

export const MOCK_MESSAGES: Record<string, ChatMessage[]> = {
  'chat-1': [
    {
      id: 'msg-1-1',
      chatId: 'chat-1',
      senderId: 'user-me',
      senderName: 'Kiss Péter',
      content: 'Szia Anna! Tudnál segíteni a napi zárásban?',
      timestamp: '2024-01-18T14:00:00Z',
      status: 'read',
      isOwn: true,
    },
    {
      id: 'msg-1-2',
      chatId: 'chat-1',
      senderId: 'user-1',
      senderName: 'Nagy Anna',
      content: 'Szia! Persze, mi a probléma?',
      timestamp: '2024-01-18T14:05:00Z',
      status: 'read',
    },
    {
      id: 'msg-1-3',
      chatId: 'chat-1',
      senderId: 'user-me',
      senderName: 'Kiss Péter',
      content: 'A kasszában van egy 5000 Ft-os eltérés, nem találom honnan jön',
      timestamp: '2024-01-18T14:10:00Z',
      status: 'read',
      isOwn: true,
    },
    {
      id: 'msg-1-4',
      chatId: 'chat-1',
      senderId: 'user-1',
      senderName: 'Nagy Anna',
      content: 'Ja, az a Kovács úr visszatérítése volt, elfelejtettem beírni. Most javítom!',
      timestamp: '2024-01-18T14:25:00Z',
      status: 'read',
    },
    {
      id: 'msg-1-5',
      chatId: 'chat-1',
      senderId: 'user-1',
      senderName: 'Nagy Anna',
      content: 'Rendben, megcsináltam a zárást!',
      timestamp: '2024-01-18T14:32:00Z',
      status: 'read',
    },
  ],
  'chat-2': [
    {
      id: 'msg-2-1',
      chatId: 'chat-2',
      senderId: 'user-me',
      senderName: 'Kiss Péter',
      content: 'Srácok, mikor érkezik a Makita alkatrész?',
      timestamp: '2024-01-18T09:00:00Z',
      status: 'read',
      isOwn: true,
    },
    {
      id: 'msg-2-2',
      chatId: 'chat-2',
      senderId: 'user-5',
      senderName: 'Tóth Gábor',
      content: 'A futár szerint ma délután',
      timestamp: '2024-01-18T09:30:00Z',
      status: 'read',
    },
    {
      id: 'msg-2-3',
      chatId: 'chat-2',
      senderId: 'user-2',
      senderName: 'Szabó Ferenc',
      content: 'A Makita fúró alkatrész megérkezett',
      timestamp: '2024-01-18T13:15:00Z',
      status: 'delivered',
    },
  ],
  'chat-3': [
    {
      id: 'msg-3-1',
      chatId: 'chat-3',
      senderId: 'user-4',
      senderName: 'Kovács János',
      content: 'Főnök, a raktárban hiányzik 3 db sarokcsiszoló',
      timestamp: '2024-01-18T09:45:00Z',
      status: 'read',
    },
    {
      id: 'msg-3-2',
      chatId: 'chat-3',
      senderId: 'user-me',
      senderName: 'Kiss Péter',
      content: 'Kérlek ellenőrizd a készletet holnapig',
      timestamp: '2024-01-18T10:00:00Z',
      status: 'read',
      isOwn: true,
    },
  ],
  'chat-4': [
    {
      id: 'msg-4-1',
      chatId: 'chat-4',
      senderId: 'user-3',
      senderName: 'Horváth Mária',
      content: 'A havi jelentés elkészült, csatoltam',
      timestamp: '2024-01-17T16:45:00Z',
      status: 'read',
    },
  ],
  'chat-5': [
    {
      id: 'msg-5-1',
      chatId: 'chat-5',
      senderId: 'user-5',
      senderName: 'Tóth Gábor',
      content: 'Szia! Holnap be tudnál jönni korábban?',
      timestamp: '2024-01-18T15:00:00Z',
      status: 'delivered',
    },
  ],
};
