import type { Permission, PermissionModule, Role, User, UserStatus } from './types';

export const USER_STATUSES: { value: UserStatus; label: string; color: string }[] = [
  { value: 'active', label: 'Aktív', color: 'bg-green-100 text-green-800' },
  { value: 'inactive', label: 'Inaktív', color: 'bg-gray-100 text-gray-800' },
  { value: 'suspended', label: 'Felfüggesztve', color: 'bg-red-100 text-red-800' },
];

export const PERMISSION_MODULES: { value: PermissionModule; label: string; icon: string }[] = [
  { value: 'auth', label: 'Hitelesítés', icon: '🔐' },
  { value: 'users', label: 'Felhasználók', icon: '👥' },
  { value: 'partners', label: 'Partnerek', icon: '🤝' },
  { value: 'inventory', label: 'Készlet', icon: '📦' },
  { value: 'rental', label: 'Bérlés', icon: '🔧' },
  { value: 'sales', label: 'Értékesítés', icon: '🛒' },
  { value: 'service', label: 'Szerviz', icon: '🔨' },
  { value: 'reports', label: 'Riportok', icon: '📊' },
  { value: 'settings', label: 'Beállítások', icon: '⚙️' },
];

export const MOCK_PERMISSIONS: Permission[] = [
  // Auth
  {
    id: 'p-001',
    code: 'auth.login',
    name: 'Bejelentkezés',
    description: 'Rendszer bejelentkezés',
    module: 'auth',
  },
  {
    id: 'p-002',
    code: 'auth.pin',
    name: 'PIN kód használat',
    description: 'Kiosk mód PIN kóddal',
    module: 'auth',
  },

  // Users
  {
    id: 'p-010',
    code: 'users.read',
    name: 'Felhasználók megtekintése',
    description: 'Felhasználó lista és részletek',
    module: 'users',
  },
  {
    id: 'p-011',
    code: 'users.create',
    name: 'Felhasználó létrehozása',
    description: 'Új felhasználó felvétele',
    module: 'users',
  },
  {
    id: 'p-012',
    code: 'users.update',
    name: 'Felhasználó módosítása',
    description: 'Felhasználó adatok szerkesztése',
    module: 'users',
  },
  {
    id: 'p-013',
    code: 'users.delete',
    name: 'Felhasználó törlése',
    description: 'Felhasználó eltávolítása',
    module: 'users',
  },
  {
    id: 'p-014',
    code: 'users.roles',
    name: 'Szerepkör kezelés',
    description: 'Szerepkörök és jogosultságok',
    module: 'users',
  },

  // Partners
  {
    id: 'p-020',
    code: 'partners.read',
    name: 'Partnerek megtekintése',
    description: 'Partner lista és részletek',
    module: 'partners',
  },
  {
    id: 'p-021',
    code: 'partners.create',
    name: 'Partner létrehozása',
    description: 'Új partner felvétele',
    module: 'partners',
  },
  {
    id: 'p-022',
    code: 'partners.update',
    name: 'Partner módosítása',
    description: 'Partner adatok szerkesztése',
    module: 'partners',
  },
  {
    id: 'p-023',
    code: 'partners.delete',
    name: 'Partner törlése',
    description: 'Partner eltávolítása',
    module: 'partners',
  },

  // Inventory
  {
    id: 'p-030',
    code: 'inventory.read',
    name: 'Készlet megtekintése',
    description: 'Készlet lista és részletek',
    module: 'inventory',
  },
  {
    id: 'p-031',
    code: 'inventory.receive',
    name: 'Bevételezés',
    description: 'Árubevételezés',
    module: 'inventory',
  },
  {
    id: 'p-032',
    code: 'inventory.adjust',
    name: 'Készlet korrekció',
    description: 'Készlet módosítás',
    module: 'inventory',
  },
  {
    id: 'p-033',
    code: 'inventory.transfer',
    name: 'Raktárközi mozgatás',
    description: 'Készlet áthelyezés',
    module: 'inventory',
  },

  // Rental
  {
    id: 'p-040',
    code: 'rental.read',
    name: 'Bérlések megtekintése',
    description: 'Bérlés lista és részletek',
    module: 'rental',
  },
  {
    id: 'p-041',
    code: 'rental.create',
    name: 'Bérlés indítása',
    description: 'Új bérlés létrehozása',
    module: 'rental',
  },
  {
    id: 'p-042',
    code: 'rental.return',
    name: 'Bérlés visszavétele',
    description: 'Bérlés lezárása',
    module: 'rental',
  },
  {
    id: 'p-043',
    code: 'rental.extend',
    name: 'Bérlés hosszabbítása',
    description: 'Bérlési időszak módosítása',
    module: 'rental',
  },

  // Sales
  {
    id: 'p-050',
    code: 'sales.read',
    name: 'Értékesítések megtekintése',
    description: 'Eladások lista',
    module: 'sales',
  },
  {
    id: 'p-051',
    code: 'sales.create',
    name: 'Értékesítés',
    description: 'Kassza használat',
    module: 'sales',
  },
  {
    id: 'p-052',
    code: 'sales.refund',
    name: 'Visszáru',
    description: 'Visszáru kezelés',
    module: 'sales',
  },
  {
    id: 'p-053',
    code: 'sales.discount',
    name: 'Kedvezmény adás',
    description: 'Kedvezmény alkalmazása',
    module: 'sales',
  },

  // Service
  {
    id: 'p-060',
    code: 'service.read',
    name: 'Munkalapok megtekintése',
    description: 'Munkalap lista',
    module: 'service',
  },
  {
    id: 'p-061',
    code: 'service.create',
    name: 'Munkalap létrehozása',
    description: 'Új munkalap felvétele',
    module: 'service',
  },
  {
    id: 'p-062',
    code: 'service.update',
    name: 'Munkalap szerkesztése',
    description: 'Munkalap módosítása',
    module: 'service',
  },
  {
    id: 'p-063',
    code: 'service.close',
    name: 'Munkalap lezárása',
    description: 'Munkalap befejezése',
    module: 'service',
  },

  // Reports
  {
    id: 'p-070',
    code: 'reports.sales',
    name: 'Értékesítési riportok',
    description: 'Eladási statisztikák',
    module: 'reports',
  },
  {
    id: 'p-071',
    code: 'reports.rental',
    name: 'Bérlési riportok',
    description: 'Bérlési statisztikák',
    module: 'reports',
  },
  {
    id: 'p-072',
    code: 'reports.inventory',
    name: 'Készlet riportok',
    description: 'Készlet statisztikák',
    module: 'reports',
  },
  {
    id: 'p-073',
    code: 'reports.financial',
    name: 'Pénzügyi riportok',
    description: 'Pénzügyi összesítők',
    module: 'reports',
  },

  // Settings
  {
    id: 'p-080',
    code: 'settings.read',
    name: 'Beállítások megtekintése',
    description: 'Rendszer beállítások',
    module: 'settings',
  },
  {
    id: 'p-081',
    code: 'settings.update',
    name: 'Beállítások módosítása',
    description: 'Rendszer konfiguráció',
    module: 'settings',
  },
];

export const MOCK_ROLES: Role[] = [
  {
    id: 'role-001',
    code: 'admin',
    name: 'Rendszergazda',
    description: 'Teljes hozzáférés minden funkcióhoz',
    permissions: MOCK_PERMISSIONS.map(p => p.id),
    isSystem: true,
    userCount: 2,
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2023-01-01T00:00:00Z',
  },
  {
    id: 'role-002',
    code: 'manager',
    name: 'Üzletvezető',
    description: 'Üzlet működtetése, riportok, felhasználók kezelése',
    permissions: [
      'p-001',
      'p-002',
      'p-010',
      'p-011',
      'p-012',
      'p-020',
      'p-021',
      'p-022',
      'p-023',
      'p-030',
      'p-031',
      'p-032',
      'p-033',
      'p-040',
      'p-041',
      'p-042',
      'p-043',
      'p-050',
      'p-051',
      'p-052',
      'p-053',
      'p-060',
      'p-061',
      'p-062',
      'p-063',
      'p-070',
      'p-071',
      'p-072',
      'p-073',
      'p-080',
    ],
    isSystem: true,
    userCount: 3,
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2023-01-01T00:00:00Z',
  },
  {
    id: 'role-003',
    code: 'cashier',
    name: 'Pénztáros',
    description: 'Kassza kezelés, értékesítés, bérlés',
    permissions: [
      'p-001',
      'p-002',
      'p-020',
      'p-030',
      'p-040',
      'p-041',
      'p-042',
      'p-050',
      'p-051',
      'p-053',
    ],
    isSystem: true,
    userCount: 5,
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2023-01-01T00:00:00Z',
  },
  {
    id: 'role-004',
    code: 'technician',
    name: 'Szervizes',
    description: 'Munkalap kezelés, szerviz műveletek',
    permissions: ['p-001', 'p-002', 'p-020', 'p-030', 'p-060', 'p-061', 'p-062', 'p-063'],
    isSystem: true,
    userCount: 4,
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2023-01-01T00:00:00Z',
  },
  {
    id: 'role-005',
    code: 'warehouse',
    name: 'Raktáros',
    description: 'Készletkezelés, bevételezés, kiadás',
    permissions: ['p-001', 'p-002', 'p-030', 'p-031', 'p-032', 'p-033', 'p-040'],
    isSystem: false,
    userCount: 2,
    createdAt: '2024-06-01T10:00:00Z',
    updatedAt: '2024-06-01T10:00:00Z',
  },
];

export const MOCK_USERS: User[] = [
  {
    id: 'u-001',
    email: 'admin@kisgepcentrum.hu',
    username: 'admin',
    firstName: 'Rendszer',
    lastName: 'Adminisztrátor',
    fullName: 'Rendszer Adminisztrátor',
    phone: '+36 1 234 5678',
    status: 'active',
    roles: ['role-001'],
    primaryRole: 'role-001',
    tenantId: 'tenant-001',
    tenantName: 'Kisgépcentrum Központ',
    lastLoginAt: '2026-01-18T09:30:00Z',
    lastLoginIp: '192.168.1.100',
    failedLoginAttempts: 0,
    locale: 'hu-HU',
    timezone: 'Europe/Budapest',
    preferences: {
      theme: 'light',
      notifications: true,
      emailNotifications: true,
    },
    hasPinCode: true,
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2026-01-18T09:30:00Z',
  },
  {
    id: 'u-002',
    email: 'kovacs.janos@kisgepcentrum.hu',
    username: 'kovacs.janos',
    firstName: 'János',
    lastName: 'Kovács',
    fullName: 'Kovács János',
    phone: '+36 30 111 2222',
    status: 'active',
    roles: ['role-002'],
    primaryRole: 'role-002',
    tenantId: 'tenant-001',
    tenantName: 'Kisgépcentrum Központ',
    lastLoginAt: '2026-01-18T08:15:00Z',
    lastLoginIp: '192.168.1.105',
    failedLoginAttempts: 0,
    locale: 'hu-HU',
    timezone: 'Europe/Budapest',
    preferences: {
      theme: 'dark',
      notifications: true,
      emailNotifications: true,
    },
    hasPinCode: true,
    createdAt: '2023-03-15T10:00:00Z',
    updatedAt: '2026-01-18T08:15:00Z',
  },
  {
    id: 'u-003',
    email: 'nagy.eva@kisgepcentrum.hu',
    username: 'nagy.eva',
    firstName: 'Éva',
    lastName: 'Nagy',
    fullName: 'Nagy Éva',
    phone: '+36 30 222 3333',
    status: 'active',
    roles: ['role-003'],
    primaryRole: 'role-003',
    tenantId: 'tenant-001',
    tenantName: 'Kisgépcentrum Központ',
    lastLoginAt: '2026-01-18T07:45:00Z',
    lastLoginIp: '192.168.1.110',
    failedLoginAttempts: 0,
    locale: 'hu-HU',
    timezone: 'Europe/Budapest',
    preferences: {
      theme: 'light',
      notifications: true,
      emailNotifications: false,
    },
    hasPinCode: true,
    createdAt: '2024-01-10T09:00:00Z',
    updatedAt: '2026-01-18T07:45:00Z',
  },
  {
    id: 'u-004',
    email: 'szabo.peter@kisgepcentrum.hu',
    username: 'szabo.peter',
    firstName: 'Péter',
    lastName: 'Szabó',
    fullName: 'Szabó Péter',
    phone: '+36 30 333 4444',
    status: 'active',
    roles: ['role-004'],
    primaryRole: 'role-004',
    tenantId: 'tenant-001',
    tenantName: 'Kisgépcentrum Központ',
    lastLoginAt: '2026-01-17T16:30:00Z',
    lastLoginIp: '192.168.1.115',
    failedLoginAttempts: 0,
    locale: 'hu-HU',
    timezone: 'Europe/Budapest',
    preferences: {
      theme: 'system',
      notifications: true,
      emailNotifications: true,
    },
    hasPinCode: true,
    createdAt: '2024-03-20T11:00:00Z',
    updatedAt: '2026-01-17T16:30:00Z',
  },
  {
    id: 'u-005',
    email: 'toth.gabor@kisgepcentrum.hu',
    username: 'toth.gabor',
    firstName: 'Gábor',
    lastName: 'Tóth',
    fullName: 'Tóth Gábor',
    phone: '+36 30 444 5555',
    status: 'active',
    roles: ['role-003', 'role-005'],
    primaryRole: 'role-003',
    tenantId: 'tenant-002',
    tenantName: 'Kisgépcentrum Budaörs',
    lastLoginAt: '2026-01-18T08:00:00Z',
    lastLoginIp: '10.0.0.50',
    failedLoginAttempts: 0,
    locale: 'hu-HU',
    timezone: 'Europe/Budapest',
    preferences: {
      theme: 'light',
      notifications: true,
      emailNotifications: true,
    },
    hasPinCode: true,
    createdAt: '2024-06-01T09:00:00Z',
    updatedAt: '2026-01-18T08:00:00Z',
  },
  {
    id: 'u-006',
    email: 'molnar.anna@kisgepcentrum.hu',
    username: 'molnar.anna',
    firstName: 'Anna',
    lastName: 'Molnár',
    fullName: 'Molnár Anna',
    phone: '+36 30 555 6666',
    status: 'inactive',
    roles: ['role-003'],
    primaryRole: 'role-003',
    tenantId: 'tenant-001',
    tenantName: 'Kisgépcentrum Központ',
    lastLoginAt: '2025-09-15T14:00:00Z',
    failedLoginAttempts: 0,
    locale: 'hu-HU',
    timezone: 'Europe/Budapest',
    preferences: {
      theme: 'light',
      notifications: false,
      emailNotifications: false,
    },
    hasPinCode: false,
    createdAt: '2024-02-01T10:00:00Z',
    updatedAt: '2025-10-01T09:00:00Z',
  },
  {
    id: 'u-007',
    email: 'kiss.laszlo@kisgepcentrum.hu',
    username: 'kiss.laszlo',
    firstName: 'László',
    lastName: 'Kiss',
    fullName: 'Kiss László',
    phone: '+36 30 666 7777',
    status: 'suspended',
    roles: ['role-003'],
    primaryRole: 'role-003',
    tenantId: 'tenant-001',
    tenantName: 'Kisgépcentrum Központ',
    lastLoginAt: '2025-12-01T10:00:00Z',
    lastLoginIp: '192.168.1.200',
    failedLoginAttempts: 5,
    lockedUntil: '2026-01-20T00:00:00Z',
    locale: 'hu-HU',
    timezone: 'Europe/Budapest',
    preferences: {
      theme: 'light',
      notifications: true,
      emailNotifications: true,
    },
    hasPinCode: true,
    createdAt: '2024-08-15T09:00:00Z',
    updatedAt: '2025-12-01T10:30:00Z',
  },
  {
    id: 'u-008',
    email: 'horvath.istvan@kisgepcentrum.hu',
    username: 'horvath.istvan',
    firstName: 'István',
    lastName: 'Horváth',
    fullName: 'Horváth István',
    phone: '+36 30 777 8888',
    status: 'active',
    roles: ['role-002'],
    primaryRole: 'role-002',
    tenantId: 'tenant-002',
    tenantName: 'Kisgépcentrum Budaörs',
    lastLoginAt: '2026-01-18T07:30:00Z',
    lastLoginIp: '10.0.0.55',
    failedLoginAttempts: 0,
    locale: 'hu-HU',
    timezone: 'Europe/Budapest',
    preferences: {
      theme: 'dark',
      notifications: true,
      emailNotifications: true,
    },
    hasPinCode: true,
    createdAt: '2024-04-01T10:00:00Z',
    updatedAt: '2026-01-18T07:30:00Z',
  },
];

export const MOCK_TENANTS = [
  { id: 'tenant-001', name: 'Kisgépcentrum Központ' },
  { id: 'tenant-002', name: 'Kisgépcentrum Budaörs' },
  { id: 'tenant-003', name: 'Kisgépcentrum Győr' },
];

export function getRoleName(roleId: string): string {
  return MOCK_ROLES.find(r => r.id === roleId)?.name ?? 'Ismeretlen';
}

export function getPermissionsByModule(module: PermissionModule): Permission[] {
  return MOCK_PERMISSIONS.filter(p => p.module === module);
}
